export default {
	LOAD_PATIENTS_SUCCESS: 'LOAD_PATIENTS_SUCCESS',
	LOAD_PATIENTS_SAGA :'LOAD_PATIENTS_SAGA',
	UPDATE_PATIENT_SUCCESS:'UPDATE_PATIENT_SUCCESS',
	UPDATE_PATIENT_SAGA:'UPDATE_PATIENT_SAGA',
	CREATE_PATIENT_SUCCESS:'CREATE_PATIENT_SUCCESS',
	CREATE_PATIENT_SAGA:'CREATE_PATIENT_SAGA',
	DELETE_PATIENT_SUCCESS:'DELETE_PATIENT_SUCCESS',
	DELETE_PATIENT_SAGA:'DELETE_PATIENT_SAGA',
	HANDLE_PATIENT_ERROR:'HANDLE_PATIENT_ERROR',
	SAVE_SUCCESS:'SAVE_SUCCESS',
	GET_PATIENT_INFO_SUCCESS: 'GET_PATIENT_INFO_SUCCESS',
	GET_PATIENT_INFO_SAGA:'GET_PATIENT_INFO_SAGA',
};